version: "2"
linters:
  default: none
  enable:
    # - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-occurrences: 5
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
  exclusions:
    generated: lax

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kahlys/codex
  exclusions:
    generated: lax
